name: Ejecutar script

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ejecutar_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4

      - name: Instalar dependencias
        run: |
          npm install --prefix "/tmp/npm" puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Configurar git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Ejecutar script
        run: |
          node ./olympus_scraping.js

      - name: Subir cambios
        run: |
          git add -A
          git commit -m "Actualizado" || echo "Sin cambios"
          git pull origin main --rebase
          git push origin main
