name: Ejecutar script

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ejecutar_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard-tools

      - name: Configurar WireGuard
        run: |
          sudo mkdir -p /etc/wireguard/
          echo "${{ secrets.WG_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf

      - name: Iniciar conexión WireGuard
        run: sudo wg-quick up wg0

      - name: Verificar conexión WireGuard
        run: |
          if ! curl --max-time 10 -s https://google.com > /dev/null; then
            echo "::error:: Conexión no establecida; revisar credenciales"
            exit 1
          fi

      - name: Configurar Node.js
        uses: actions/setup-node@v4

      - name: Instalar dependencias
        run: |
          npm install --prefix "/tmp/npm" puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Configurar git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Ejecutar script
        run: |
          node ./olympus_scraping.js

      - name: Subir cambios
        run: |
          git add -A
          git commit -m "Actualizado" || echo "Sin cambios"
          git pull origin main --rebase
          git push origin main
